# ══════════════════════════════════════════════
#  Gamilha — Configuration des clés API
#  Mettre vos vraies clés ici
# ══════════════════════════════════════════════

# Ably (temps réel) — https://ably.com → App → API Keys → Root key
ably.key=PZY-tA.XRFVAw:Kr00VrcHWY8AlQC3qivnmQcCkmre0pHDkXG3fBb-GuM

# api.video — https://api.video → Dashboard → API Keys
apivideo.key=y5mdHtjGJTqvv4AShzWg68oz0fdBRpRFMOLeTxOyS4D

# Base de données
db.url=jdbc:mysql://localhost:3306/defaultdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=
